# Generated by Django 5.1.4 on 2025-01-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalaceapp', '0003_pettrainingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('appointment_date', models.DateField()),
            ],
        ),
    ]
