# Generated by Django 5.1.2 on 2025-01-31 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalaceapp', '0005_orderhistory_delete_groomingappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='productWithQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petpalaceapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petpalaceapp.productwithquantity'),
        ),
    ]
