# Generated by Django 5.1.4 on 2025-01-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalaceapp', '0002_product_category_product_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_age', models.PositiveIntegerField(default=0)),
                ('pet_breed', models.CharField(blank=True, max_length=150, null=True)),
                ('trainer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('session_date', models.DateField()),
                ('session_duration', models.DurationField(help_text='Duration of the session (hh:mm:ss)')),
                ('training_type', models.CharField(help_text='e.g., Obedience, Agility, Behavioral', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pet Training Data',
                'verbose_name_plural': 'Pet Training Data',
                'ordering': ['-session_date'],
            },
        ),
    ]
