# Generated by Django 5.1.4 on 2025-01-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalaceapp', '0005_products_delete_groomingappointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
