# Generated by Django 5.1.4 on 2025-01-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalaceapp', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetBoarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('standard', 'Standard Boarding'), ('luxury', 'Luxury Boarding'), ('premium', 'Premium Boarding')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('drop_off_time', models.TimeField()),
                ('payment_method', models.CharField(max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
