# Generated by Django 5.1.4 on 2025-01-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalaceapp', '0008_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_age', models.PositiveIntegerField()),
                ('pet_breed', models.CharField(blank=True, max_length=100, null=True)),
                ('groomer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('session_date', models.DateField()),
                ('services', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
