# Generated by Django 5.1.4 on 2025-01-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalaceapp', '0009_groomingsession_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('basic', 'Basic Grooming'), ('deluxe', 'Deluxe Grooming'), ('premium', 'Premium Grooming')], max_length=20)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('pet_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
