# Generated by Django 5.1.4 on 2025-01-28 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpalaceapp', '0011_trainingservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='user',
        ),
        migrations.AddField(
            model_name='pet',
            name='available_for_adoption',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='bio',
            field=models.TextField(default='No bio provided'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='expertise',
            field=models.CharField(blank=True, choices=[('obedience', 'Obedience Training'), ('agility', 'Agility Training'), ('behavioral', 'Behavioral Training'), ('puppy', 'Puppy Training')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='petpalaceapp.pet'),
        ),
    ]
